core/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap

from core import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('order/', include('order.urls')),
    path('', include('shop.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path, re_path
from django.contrib.auth.views import (PasswordResetConfirmView, PasswordResetDoneView,
                                       PasswordResetCompleteView, PasswordResetView)
from django.views.decorators.csrf import csrf_exempt

from shop import views


urlpatterns = [
    path('signin/', views.SigninView.as_view(), name='signin'),
    path('signup/', views.SignupView.as_view(), name='signup'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('user/password/reset/', PasswordResetView.as_view(), name="password_reset"),
    path('user/password/reset/done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    re_path(r'^user/password/reset/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/', PasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    path('user/password/reset/complete/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('profile/orders/', views.ProfileOrdersView.as_view(), name='profile_orders'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('category/<slug:slug>/', views.CategoryView.as_view(), name='category'),
    path('search/', csrf_exempt(views.SearchView.as_view()), name='search'),
    path('cart/', views.CartView.as_view(), name='cart_detail'),
    path('cart-add/<int:product_id>)/', views.cart_add, name='cart_add'),
    path('cart-remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
    path('product/<int:pk>/', views.ProductView.as_view(), name='product'),
    path('', views.HomepageView.as_view(), name='index'),
]

shop/models.py
import datetime

from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone

from stdimage import StdImageField


# ========================================= Abstract models ========================================= #

class BaseModel(models.Model):
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, unique=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    description = models.TextField(blank=True)

    def __str__(self):
        return self.name

    class Meta:
        abstract = True

# ========================================= /Abstract models ========================================= #


# ============================================ User data ============================================= #

class UserProfile(models.Model):
    ip = models.CharField(max_length=40, blank=True)
    django_user = models.OneToOneField(User, on_delete=models.CASCADE)
    city = models.CharField(max_length=30, blank=True)
    postal_code = models.CharField(max_length=10, blank=True)
    address = models.TextField(blank=True)
    phone = models.CharField(max_length=16, blank=True)

    def __str__(self):
        return self.django_user.email

    class Meta:
        verbose_name = 'User profile'
        verbose_name_plural = 'User profiles'


class Visitor(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    product = models.ForeignKey('Product', related_name='product_visitor', on_delete=models.CASCADE)
    ip = models.CharField(max_length=40)

    def __str__(self):
        return self.product.name

    class Meta:
        verbose_name = 'Visitor'
        verbose_name_plural = 'Visitors'
        ordering = ['-created']


# ============================================ /User data ============================================= #


# =========================================== Product data ============================================ #

class Category(BaseModel):
    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'
        ordering = ['name']


class ProductImage(models.Model):
    image = StdImageField("Image", upload_to='product/image/%Y/%m/%d', variations={
        'thumbnail': (153, 153, True), 'medium': (263, 263, True), 'large': (600, 600, True)})

    class Meta:
        verbose_name = 'Product image'
        verbose_name_plural = 'Product images'


class ProductQuerySet(models.QuerySet):
    def available(self):
        return self.filter(is_available=True)


class Product(BaseModel):
    category = models.ManyToManyField(Category, related_name='category_product')
    image = models.ManyToManyField(ProductImage, blank=True, related_name='image_product')
    price = models.DecimalField(u"Price", decimal_places=2, max_digits=10, default=0)
    is_available = models.BooleanField(default=True)
    views = models.IntegerField(u'Views', default=0)
    objects = ProductQuerySet.as_manager()

    def is_new(self):
        date_limit = timezone.now() - datetime.timedelta(days=30)
        if self.created > date_limit:
            return True
        return False

    def get_price(self):
        return '{0:,}'.format(self.price).replace(',', ' ')

    class Meta:
        verbose_name = 'Product'
        verbose_name_plural = 'Products'
        ordering = ["name"]

# =========================================== /Product data ============================================ #

shop/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm as RegistrationForm

from shop.models import UserProfile

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)


class ProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ("address", "phone", "postal_code", "city")


class SigninForm(AuthenticationForm):

    class Meta:
        fields = ("username", "password")


class SignupForm(RegistrationForm):
    email = forms.EmailField(required=True)
    username = forms.CharField(max_length=50)
    first_name = forms.CharField(max_length=50, required=True)
    last_name = forms.CharField(max_length=50, required=True)

    class Meta(RegistrationForm.Meta):
        fields = ("username", "email", "first_name", "last_name")

shop/views.py
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect
from django.views import generic
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_POST
from django.contrib.auth import logout as django_logout, login

from core.helpers import json_response, get_client_ip
from shop.cart import Cart
from shop.forms import CartAddProductForm, ProfileForm, SigninForm, SignupForm
from shop.models import Product, UserProfile, Category


# ============================================= Shop ============================================== #

class HomepageView(generic.ListView):
    template_name = 'index.html'
    queryset = Product.objects.available().order_by('-created')[:6]

    def get_context_data(self, **kwargs):
        context_data = super(HomepageView, self).get_context_data(**kwargs)
        context_data['meta_title'] = 'Shop'
        context_data['best_products'] = Product.objects.available().order_by('-views')[:6]
        return context_data


class CategoryView(generic.DetailView):
    template_name = 'category.html'
    model = Category

    def get_context_data(self, **kwargs):
        context_data = super(CategoryView, self).get_context_data(**kwargs)
        context_data['meta_title'] = self.object.name
        context_data['object_list'] = self.object.category_product.available()
        return context_data


class SearchView(generic.ListView):
    template_name = 'search.html'
    paginate_by = 30

    def get_queryset(self):
        q = self.request.POST.get('q', '')
        products = Product.objects.available().filter(name__icontains=q)
        category_slug = self.request.POST.get('category', '')
        if category_slug:
            category = get_object_or_404(Category, slug=category_slug)
            products = products.filter(category=category)
        return products

    def get_context_data(self, **kwargs):
        context_data = super(SearchView, self).get_context_data(**kwargs)
        q = self.request.POST.get('q', '')
        context_data['q'] = q
        context_data['meta_title'] = 'Продукты по запросу ' + q
        return context_data

    def post(self, request, *args, **kwargs):
        return self.get(request, *args, **kwargs)


class ProductView(generic.DetailView):
    model = Product
    template_name = 'product.html'

    def get_context_data(self, **kwargs):
        context_data = super(ProductView, self).get_context_data(**kwargs)
        context_data['related_products'] = Product.objects.available().filter(
            category=self.object.category.first()).exclude(id=self.object.id)
        context_data['cart_product_form'] = CartAddProductForm()
        return context_data


class CartView(generic.TemplateView):
    template_name = 'cart.html'

    def get_context_data(self, **kwargs):
        context_data = super(CartView, self).get_context_data(**kwargs)
        context_data['cart'] = Cart(self.request)
        return context_data


@require_POST
@csrf_exempt
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(
            product=product, quantity=cd['quantity'], update_quantity=cd['update']
        )
    return redirect('cart_detail')


@require_POST
@csrf_exempt
def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart_detail')

# ============================================= /Shop ============================================== #


# ============================================ Profile ============================================= #

class ProfileView(LoginRequiredMixin, generic.ListView):
    queryset = []
    template_name = 'profile/profile.html'

    def get_context_data(self, **kwargs):
        context_data = super(ProfileView, self).get_context_data(**kwargs)
        context_data['message'] = self.kwargs.get('message', '')
        context_data['meta_title'] = 'Мой профиль'
        context_data['form'] = ProfileForm(instance=self.request.user.userprofile)
        return context_data

    def post(self, request, *args, **kwargs):
        u = get_object_or_404(UserProfile, django_user=request.user)
        if 'old_password' in request.POST:
            form = PasswordChangeForm(request.user, request.POST)
            if form.is_valid():
                form.save()
                message = 'Изменения сохранены'
            else:
                message = '<br>'.join([form.fields[k].label + ': ' + v[0] for k, v in form.errors.items()])
        else:
            form = ProfileForm(request.POST, request.FILES, instance=u)
            if form.is_valid():
                user_profile = form.save()
                user = user_profile.django_user
                user.email = request.POST.get('email')
                user.first_name = request.POST.get('first_name')
                user.last_name = request.POST.get('last_name')
                user.save()
                self.request.user = user
                message = 'Изменения сохранены'
            else:
                message = '<br>'.join([form.fields[k].label + ': ' + v[0] for k, v in form.errors.items()])
        self.kwargs['message'] = message
        return self.get(request, *args, **kwargs)


class SigninView(generic.FormView):
    form_class = SigninForm
    success_url = "/"
    template_name = 'profile/signin.html'

    def get_context_data(self, **kwargs):
        context_data = super(SigninView, self).get_context_data(**kwargs)
        context_data['path'] = self.request.META.get('HTTP_REFERER', '/')
        return context_data

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        self.success_url = self.request.POST.get("next", "/")
        self.user = form.get_user()
        login(self.request, self.user, backend='django.contrib.auth.backends.ModelBackend')
        return json_response({'success': True, 'url': self.success_url})

    def form_invalid(self, form):
        return json_response({
            'success': False,
            'errors': '<br>'.join([v[0] for k, v in form.errors.items()])
        })


class SignupView(generic.FormView):
    form_class = SignupForm
    success_url = "/"
    template_name = 'profile/signup.html'

    def get_context_data(self, **kwargs):
        context_data = super(SignupView, self).get_context_data(**kwargs)
        context_data['path'] = self.request.META.get('HTTP_REFERER', '/')
        return context_data

    def post(self, request, *args, **kwargs):
        form = SignupForm({
            "username": request.POST.get('email'),
            "email": request.POST.get('email'),
            "password1": request.POST.get('password1'),
            "password2": request.POST.get('password2'),
            "first_name": request.POST.get('first_name'),
            "last_name": request.POST.get('last_name'),
        })
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        self.success_url = self.request.POST.get("next", "/")
        self.user = form.save()
        if self.user:
            user_profile = UserProfile(
                django_user=self.user,
                ip=get_client_ip(self.request),
            )
            user_profile.save()
            login(self.request, self.user, backend='django.contrib.auth.backends.ModelBackend')
        return json_response({'success': True, 'url': self.success_url})

    def form_invalid(self, form):
        return json_response({
            'success': False,
            'errors': '<br>'.join([v[0] for k, v in form.errors.items()])
        })


class LogoutView(generic.View):

    def get(self, request):
        django_logout(request)
        return HttpResponseRedirect(request.GET.get('next', '/'))


class ProfileOrdersView(LoginRequiredMixin, generic.ListView):
    queryset = []
    template_name = 'profile/orders.html'

    def get_context_data(self, **kwargs):
        context_data = super(ProfileOrdersView, self).get_context_data(**kwargs)
        context_data['orders'] = self.request.user.order_set.all()
        return context_data

# ============================================ /Profile ============================================= #

shop/templates/base.html
<!DOCTYPE html>
<html lang="ru">
	<head>

		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">

		<title>{{ meta_title }}</title>

 		<link href="https://fonts.googleapis.com/css?family=Montserrat:400,500,700" rel="stylesheet">
 		<link type="text/css" rel="stylesheet" href="/static/css/bootstrap.min.css"/>
 		<link type="text/css" rel="stylesheet" href="/static/css/slick.css"/>
 		<link type="text/css" rel="stylesheet" href="/static/css/slick-theme.css"/>
        <link type="text/css" rel="stylesheet" href="/static/css/nouislider.min.css"/>
 		<link rel="stylesheet" href="/static/css/font-awesome.min.css">
 		<link type="text/css" rel="stylesheet" href="/static/css/style.css"/>

		<!--[if lt IE 9]>
		  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
		  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
		<![endif]-->

    </head>
	<body>
		<!-- HEADER -->
        {% include 'includes/header.html' %}
		<!-- /HEADER -->

		<!-- NAVIGATION -->
        {% include 'includes/menu.html' %}
		<!-- /NAVIGATION -->

        {% block content %}{% endblock %}

        <!-- FOOTER -->
        {% include 'includes/footer.html' %}
		<!-- /FOOTER -->

		<!-- jQuery Plugins -->
		<script src="/static/js/jquery.min.js"></script>
		<script src="/static/js/bootstrap.min.js"></script>
		<script src="/static/js/slick.min.js"></script>
		<script src="/static/js/nouislider.min.js"></script>
		<script src="/static/js/jquery.zoom.min.js"></script>
		<script src="/static/js/main.js"></script>

	</body>
</html>

shop/templates/cart.html
{% extends 'base.html' %}

{% block content %}

    <!-- SECTION -->
    <div class="section" xmlns="http://www.w3.org/1999/html">
        <div class="container">
            <div class="row">

                <div class="col-md-12">
                    <div class="section-title">
                        <h1 class="title">Корзина</h1>
                    </div>
                </div>

                <!-- Cart -->
                <div>
                    {% for item in cart %}
                        {% with product=item.product %}
                        <form action="{% url "cart_remove" product.id %}" method="post">
                            <div class="cart-item">
                                <button class="delete" type="submit" title="Удалить"><i class="fa fa-close"></i></button>
                                <div class="cart-left">
                                    <img src="{{ product.image.first.image.thumbnail.url }}" alt="">
                                </div>
                                <div class="cart-right">
                                    <div class="cart-name">{{ product.name }}</div>
                                    <div class="cart-price">{{ item.quantity }} x <span>{{ item.price }}₽</span></div>
                                    <div class="cart-total-price">Сумма: <span>{{ item.total_price }}₽</span></div>
                                </div>
                            </div>
                        </form>
                        {% endwith %}
                    {% endfor %}
                </div>
                <div class="cart-all-price">
                    Всего <span>{{ cart|length }}</span> товаров на сумму <span>{{ cart.get_total_price }}₽</span>
                </div>
                <div class="button-block">
                    <a href="{% url 'order' %}" class="primary-btn order-submit">оформить заказ</a>
                </div>
                <!-- /Cart -->

            </div>
        </div>
    </div>
    <!-- /SECTION -->
    <div class="indent"></div>

{% endblock %}

shop/templates/category.html
{% extends 'base.html' %}

{% block content %}

    <!-- SECTION -->
    <div class="section">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="section-title">
                        <h1 class="title">{{ object.name }}</h1>
                    </div>
                </div>
                {% include 'includes/list.html' %}
            </div>
        </div>
    </div>
    <!-- /SECTION -->

{% endblock %}

shop/templates/index.html
{% extends 'base.html' %}

{% block content %}

    <!-- SECTION -->
    <div class="section">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="section-title">
                        <h3 class="title">Новинки</h3>
                    </div>
                </div>
                {% include 'includes/list.html' %}
            </div>
        </div>
    </div>
    <!-- /SECTION -->

    <!-- SECTION -->
    <div class="section">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="section-title">
                        <h3 class="title">Популярные</h3>
                    </div>
                </div>
                {% include "includes/list.html" with object_list=best_products %}
            </div>
        </div>
    </div>
    <!-- /SECTION -->
    <div class="indent"></div>

{% endblock %}

shop/templates/product.html
{% extends 'base.html' %}

{% block content %}

    <!-- BREADCRUMB -->
    {% include 'includes/breadcrumb.html' %}
    <!-- /BREADCRUMB -->

    <div class="section">
        <div class="container">
            <div class="row">

                <!-- Product main img -->
                <div class="col-md-5 col-md-push-2">
                    <div id="product-main-img">
                        {% for image in object.image.all %}
                        <div class="product-preview">
                            <img src="{{ image.image.large.url }}" alt="">
                        </div>
                        {% endfor %}
                    </div>
                </div>
                <!-- /Product main img -->

                <!-- Product thumb imgs -->
                <div class="col-md-2  col-md-pull-5">
                    <div id="product-imgs">
                        {% for image in object.image.all %}
                        <div class="product-preview">
                            <img src="{{ image.image.large.url }}" alt="">
                        </div>
                        {% endfor %}
                    </div>
                </div>
                <!-- /Product thumb imgs -->

                <!-- Product details -->
                <div class="col-md-5">
                    <div class="product-details">
                        <h1 class="product-name">{{ object.name }}</h1>
                        <div>
                            <h3 class="product-price">{{ object.price }}₽</h3>
                            <span class="product-available">
                                {% if object.is_available %}Есть в наличии{% else %}Нет в наличии{% endif %}
                            </span>
                        </div>
                        <p>{% autoescape off %}{{ object.description }}{% endautoescape %}</p>

                        <form action="{% url "cart_add" object.id %}" method="post">
                            <div class="add-to-cart">
                                <div class="qty-label">
									<div class="input-number">
										<input type="number" name="quantity" value="1">
										<span class="qty-up">+</span>
										<span class="qty-down">-</span>
									</div>
								</div>
                                <input type="hidden" name="update" value="False" id="id_update">
                                <button type="submit" class="add-to-cart-btn">
                                    <i class="fa fa-shopping-cart"></i> добавить в корзину
                                </button>
                            </div>
                        </form>

                        <ul class="product-links">
                            <li>Категории:</li>
                            {% for category in object.category.all %}
                            <li><a href="{% url 'category' category.slug %}">{{ category.name }}</a></li>
                            {% endfor %}
                        </ul>

                    </div>
                </div>
                <!-- /Product details -->

            </div>
        </div>
    </div>

    <!-- Section -->
    <div class="section">
        <div class="container">
            <div class="row">

                <div class="col-md-12">
                    <div class="section-title text-center">
                        <h3 class="title">Похожие продукты</h3>
                    </div>
                </div>

                {% for product in related_products %}
                <!-- product -->
                <div class="col-md-3 col-xs-6">
                    <div class="product">
                        <div class="product-img">
                            <a href="{% url 'product' product.pk %}">
                                <img src="{{ product.image.first.image.medium.url }}" alt="">
                            </a>
                            {% if object.is_new %}
                            <div class="product-label">
                                <span class="new">Новинка</span>
                            </div>
                            {% endif %}
                        </div>
                        <div class="product-body">
                            <p class="product-category">
                                {% for category in product.category.all %}
                                {{ category.name }}
                                {% if not forloop.last %},{% endif %}
                                {% endfor %}
                            </p>
                            <h3 class="product-name">
                                <a href="{% url 'product' product.pk %}">{{ product.name }}</a>
                            </h3>
                            <h4 class="product-price">{{ product.price }}₽</h4>
                        </div>
                    </div>
                </div>
                <!-- /product -->
                {% endfor %}

            </div>
        </div>
        <br><br>
    </div>
    <!-- /Section -->

{% endblock %}

shop/templates/search.html
{% extends 'base.html' %}

{% block content %}

    <!-- SECTION -->
    <div class="section">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="section-title">
                        <h1 class="title">Поиск по запросу «{{ q }}»</h1>
                    </div>
                </div>
                {% include 'includes/list.html' %}
            </div>
        </div>
    </div>
    <!-- /SECTION -->

{% endblock %}